[server]
port = 8501
runOnSave = true
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"
font = "sans serif"

